name: Trigger an Azure Machine Learning job with push to main

on:
  push:
    branches:
      - main


jobs:
  experiment_job:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_EXPERIMENT }}
      run: |
        az extension add -n ml -y
        az configure --defaults location=Brazil South group=rg-dp100-labs workspace=mlw-dp100-labs
    - name: Trigger the Experiment Azure Machine Learning Job
      run: az ml job submit --file src/experiment_job.yml

  production_job:
    needs: experiment_job
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_PRODUCTION }}
      run: |
        az extension add -n ml -y
        az configure --defaults location=Brazil South group=rg-dp100-labs workspace=mlw-dp100-labs
    - name: Trigger the Production Azure Machine Learning Job
      run: az ml job submit --file src/production_job.yml --stream
