name: Manually trigger an Azure Machine Learning job

on:
  push:
    branches:
      - main

jobs:
  experiment_job:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Trigger the experiment Azure Machine Learning Job
      run: az ml job submit --file src/experiment_job.yml --resource-group rg-dp100-labs --workspace-name mlw-dp100-labs

  production_job:
    needs: experiment_job
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Trigger the production Azure Machine Learning Job
      run: az ml job submit --file src/production_job.yml --resource-group rg-dp100-labs --workspace-name mlw-dp100-labs --stream


