name: Deploy Latest Model

on:
  pull_request:

jobs:
  deploy_model:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Online Endpoint Create
      run: az ml online-endpoint create --name diabetes-mlflow -f ./mslearn-aml-cli/Allfiles/Labs/05/mlflow-endpoint/create-endpoint.yml --resource-group rg-dp100-labs --workspace-name mlw-dp100-labs
    - name: Deploy Model
      run: az ml online-deployment create --name mlflow-deployment --endpoint diabetes-mlflow -f ./mslearn-aml-cli/Allfiles/Labs/05/mlflow-endpoint/mlflow-deployment.yaml --all-traffic --resource-group rg-dp100-labs --workspace-name mlw-dp100-labs
